### ISSUE TITLE
recommended approach on how to style file-uploader from parent context

### ISSUE THREAD

**Issue by halafi** [uploadcare/blocks#410]
the only way I found to style the web-component was using JS

1. query what you want to style on the shadow DOM
2. set styles with JS

```js
const shadowRoot = document.querySelector('lr-file-uploader-regular')?.shadowRoot;
const button = shadowRoot.querySelector('button');
button.style.setProperty('width', '100%');
```

another alternative is to edit the CDN provided css file passed as `css-src`

the 1st approach leads to flash of unstyled content, the 2nd to maintaining a custom css file, is there a better way?

thanks

**Comment by nd0ut** [comment]
Hey @halafi,

Blocks docs don't cover this yet, but Symbiote.js has a `shadowStyles` setter that allows you to insert a custom stylesheet into the shadow dom. You can find more information on this at https://symbiotejs.org/docs/Styling.html.

Here's an example of how you can use it:

```html
<script type="module">
  import * as LR from '@uploadcare/blocks';

  class MyRegularUploader extends LR.FileUploaderRegular {}
  MyRegularUploader.shadowStyles = /* css */ `
    :host * {
      background: red !important;
    }
  `;

  LR.registerBlocks({ ...LR, MyRegularUploader });
</script>

<lr-my-regular-uploader css-src="path-to-base-css"></lr-my-regular-uploader>
```

Please note that there may be a flickering dropzone on the uploader button, but this is a bug specific to the component and will be fixed in the next release.

**Comment by nd0ut** [comment]
Another option is to use the bundler and postcss power.

```css
@import '@uploadcare/blocks/web/file-uploader-regular.min.css';

:host * {
  background: red !important;
}
```

```js
// resolve public URL for the bundled css
import cssSrc from './uploader.css?url`
```

```jsx
<lr-file-uploader-regular css-src={cssSrc}></lr-file-uploader-regular>
```

This approach may depend heavily on the project's stack. It is possible with webpack but requires complex configuration. Vite handles this by default for development environment only, and may have some buggy behavior in production mode.

**Comment by halafi** [comment]
that's very useful, thanks!
